# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App 

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
      - '.husky'
      - '.github/**'
      - '**/*.csv'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: yarn install, build, and test
        run: |
          yarn install globle @nestjs/cli
          yarn install
          yarn run build

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'budget-divider'
          slot-name: 'Production'
          package: .

